version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8189:8189"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_PORT}/${DB_USERNAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_JACKSON_TIME_ZONE=Europe/Moscow
      - SPRING_JACKSON_DATE_FORMAT=yyyy-MM-dd
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_USERNAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data: